; === AHK_Filter MANAGED BLOCK BEGIN ===
; Auto-generated by AHK_Filter — do not edit this block by hand.
#Persistent
#InstallKeybdHook
DetectHiddenWindows, On
OnMessage(32769, "__AHK_Filter_OnMsg")
__AHK_Filter_Ready := 1
Suspend, On

__AHK_Filter_OnMsg(wParam, lParam)
{
    if (wParam = 1)
        Suspend, Off
    else if (wParam = 0)
        Suspend, On
    else if (wParam = 3)
        return 1
    return 0
}
; === AHK_Filter MANAGED BLOCK END ===

; ===== 右键按住连发 K =====
$RButton::
    SendInput, {RButton Down}
    SetTimer, SendK, 250
    KeyWait, RButton
    SetTimer, SendK, Off
    SendInput, {RButton Up}
return

SendK:
    SendInput, {k down}
    Sleep, 10
    SendInput, {k up}
return
