; === AHK_Filter MANAGED BLOCK BEGIN ===
; Auto-generated by AHK_Filter — do not edit this block by hand.
#Persistent
#InstallKeybdHook
DetectHiddenWindows, On
OnMessage(32769, "__AHK_Filter_OnMsg")
__AHK_Filter_Ready := 1
Suspend, On

__AHK_Filter_OnMsg(wParam, lParam)
{
    if (wParam = 1)
        Suspend, Off
    else if (wParam = 0)
        Suspend, On
    else if (wParam = 3)
        return 1
    return 0
}
; === AHK_Filter MANAGED BLOCK END ===

SetStoreCapsLockMode, Off
#D::return

; ===== 中键 = 模拟左键（支持拖拽） =====
$MButton::
    SendInput, {LButton Down}
    KeyWait, MButton
    SendInput, {LButton Up}
return

; ===== 左键按住 = 高速连发逗号 ,（间隔 12ms） =====
$LButton::
    SetTimer, FastComma, 12
    KeyWait, LButton
    SetTimer, FastComma, Off
return

FastComma:
    SendInput, {,}
return
