; === AHK_Filter MANAGED BLOCK BEGIN ===
; Auto-generated by AHK_Filter — do not edit this block by hand.
#Persistent
DetectHiddenWindows, On
OnMessage(32769, "__AHK_Filter_OnMsg")
__AHK_Filter_Ready := 1

__AHK_Filter_OnMsg(wParam, lParam)
{
    if (wParam = 1)
        Suspend, Off
    else if (wParam = 0)
        Suspend, On
    else if (wParam = 3)
        return 1
    return 0
}
; === AHK_Filter MANAGED BLOCK END ===

; ===== 右键按住连发 K =====
; 由 AHK_Filter 统一管理（首次运行时会被注入包裹块）。
$RButton::
    SendInput, {RButton Down}
    SetTimer, SendK, 250
    KeyWait, RButton
    SetTimer, SendK, Off
    SendInput, {RButton Up}
return

SendK:
    SendInput, {sc025 down}
    Sleep, 10
    SendInput, {sc025 up}
return
