; === AHK_Filter MANAGED BLOCK BEGIN ===
; Auto-generated by AHK_Filter — do not edit this block by hand.
#Persistent
DetectHiddenWindows, On
OnMessage(32769, "__AHK_Filter_OnMsg")
__AHK_Filter_Ready := 1

__AHK_Filter_OnMsg(wParam, lParam)
{
    if (wParam = 1)
        Suspend, Off
    else if (wParam = 0)
        Suspend, On
    else if (wParam = 3)
        return 1
    return 0
}
; === AHK_Filter MANAGED BLOCK END ===

; ===== 滚轮双击高速发 "2" =====
; 由 AHK_Filter 统一管理（首次运行时会被注入包裹块）。
global WheelUpTimer := 0, WaitingForSecondWheelUp := false
WheelUp::
    if (WaitingForSecondWheelUp) {
        SetTimer, WheelUpTimeout, Off
        WheelUpTimer := 0
        WaitingForSecondWheelUp := false
        SetTimer, Rapid2, 25
        SetTimer, StopRapid2, -1200
    } else {
        WaitingForSecondWheelUp := true
        SetTimer, WheelUpTimeout, -500
    }
return
WheelUpTimeout:
    WaitingForSecondWheelUp := false
return
Rapid2:
    SendInput, 2
return
StopRapid2:
    SetTimer, Rapid2, Off
return
