"""Inject / update AHK_Filter managed blocks into AutoHotkey v1.1 scripts."""

from __future__ import annotations

import re
from pathlib import Path

BEGIN = "; === AHK_Filter MANAGED BLOCK BEGIN ==="
END = "; === AHK_Filter MANAGED BLOCK END ==="

# Custom WM message handled by OnMessage inside each script.
FILTER_MSG = 0x8001  # enable=1, disable=0, ping=3

MANAGED_BLOCK = f"""{BEGIN}
; Auto-generated by AHK_Filter — do not edit this block by hand.
#Persistent
#InstallKeybdHook
DetectHiddenWindows, On
OnMessage({FILTER_MSG}, "__AHK_Filter_OnMsg")
__AHK_Filter_Ready := 1
Suspend, On

__AHK_Filter_OnMsg(wParam, lParam)
{{
    if (wParam = 1)
        Suspend, Off
    else if (wParam = 0)
        Suspend, On
    else if (wParam = 3)
        return 1
    return 0
}}
{END}
"""

_BLOCK_RE = re.compile(
    re.escape(BEGIN) + r".*?" + re.escape(END) + r"\r?\n?",
    re.DOTALL,
)


def has_managed_block(text: str) -> bool:
    return BEGIN in text and END in text


def strip_managed_block(text: str) -> str:
    return _BLOCK_RE.sub("", text)


def ensure_managed_block(path: Path) -> bool:
    """
    Ensure the managed block is present and up to date at the top of the file.
    Returns True if the file was modified.
    """
    original = path.read_text(encoding="utf-8-sig")
    body = strip_managed_block(original).lstrip("\ufeff")
    new_text = MANAGED_BLOCK.rstrip() + "\n\n" + body.lstrip("\n")
    if not new_text.endswith("\n"):
        new_text += "\n"
    if original.replace("\r\n", "\n") == new_text.replace("\r\n", "\n"):
        return False
    path.write_text(new_text, encoding="utf-8", newline="\n")
    return True


def ensure_all(paths: list[Path]) -> list[Path]:
    changed: list[Path] = []
    for path in paths:
        if ensure_managed_block(path):
            changed.append(path)
    return changed
